###########################
#    Mastodon state bot   #
###########################

# App Info
app:
  # [String] Name of the app
  name: "state"
  # [String] Kewword to check
  keyword: "frikistatus"

# Mastobot config
bot:
  # [String] Name of the app
  app_name: "state"
  # [Bool] Force log in
  force_login: False
  # [String] Name of the secrets directory
  secrets_directory: "secrets"
  # [String] Name of the secrets file path
  secrets_file_path: "secrets.txt"
  # [String] Name of the config directory
  config_directory: "config"
  # [String] Name of the config file path
  config_file_path: "config.txt"

# Testing options
testing:
  # [Bool] Disable push the answer to Mastodon
  disable_push_answer: False
  # [Bool] Disable push the answer to Mastodon
  disable_dismis_notification: False

# Logging config
logger:
  # [Integer] Log level: NOTSET=0 | DEBUG=10 | INFO=20 | WARN=30 | ERROR=40 | CRITICAL=50
  loglevel: 20
  # [String] Name of the logger
  name: "mastostatus_bot"
  # [Bool] Dump the log into a file
  to_file: False
  # [String] Directory of the logger
  directory: "log"
  # [String] Filename of the log file
  filename: "mastostatus_bot.log"
  # [Bool] Dump the log into a stdout
  to_stdout: True
  # [String] Format of the log
  format: "[%(asctime)s] %(levelname)-8s %(name)-12s %(message)s"
